Authentication / Signin
open-ecommerce-api/store-engine pull request #75
Opened 2023-04-09 00:53 UTC by zamaniamin

I coded the `user Sign-in`, pleas test and review the code and give me your feedback. thank you.

**note: you can test as `superuser`, it is temporary sorry.**

2023-04-10 15:27 UTC, zamaniamin commented
I will start this issues:

1. reset pass word
2. change password
3. change email

2023-04-10 15:29 UTC, zamaniamin reviewed
It seems right

2023-04-10 15:45 UTC, alirahmnicode commented on users/models.py
I think it's better to move "UserManager" in managers.py

2023-04-10 16:25 UTC, zamaniamin commented on users/models.py
> +    USERNAME_FIELD = 'email'
for the future release

2023-04-10 16:28 UTC, zamaniamin commented on users/models.py
Yes, thanks, I will update code.

2023-04-10 18:48 UTC, aminm08 requested changes

2023-04-10 18:56 UTC, zamaniamin commented on users/serializers.py
> +    confirm_password = serializers.CharField(min_length=8, write_only=True)
nice, updated.

2023-04-10 20:35 UTC, parsariyahi requested changes
Because this is an API I suggest to use API keyword behind each path ```path("/api/user/signup")```.
I think its better and looks nicer.
For each part of our app we can use some sort of pattern like ```path("/api/{APP_NAME}/{ACTION}"```
And one thing is that if you wanna have different releases, you will need versioning the api, in this way if you make changes in your api, there won't be much refactoring on front-end side.
you can handle this with just simple solutions like adding ``vx`` -> ``v1`` after api keyword.
## Final form
```path("api/v1/{APP_NAME}/", include('{APP_NAME}.urls'))```

2023-04-10 20:49 UTC, zamaniamin commented
> Because this is an API I suggest to use API keyword behind each path `path("/api/user/signup")`. I think its better and looks nicer. For each part of our app we can use some sort of pattern like `path("/api/{APP_NAME}/{ACTION}"` And one thing is that if you wanna have different releases, you will need versioning the api, in this way if you make changes in your api, there won't be much refactoring on front-end side. you can handle this with just simple solutions like adding `vx` -> `v1` after api keyword.
> ## Final form
> 
> `path("api/v1/{APP_NAME}/", include('{APP_NAME}.urls'))`

well, but if I set the routes like your suggestion, we have some config conflict with `swagger`. so we need to sync this with swagger.
if you are interested in, we can create a new issue and leave it to you.

2023-04-14 21:20 UTC, MohammadShapouri commented on users/serializers.py
> +            user.is_active = False
Instead of creating a user then changing its "is_active" to false and updating it (2 queries), we can set "is_active" to false during creating that user (1 query). To achieve this purpose, we can pass "is_active = False" as an attribute to serializer's .save() method in views.py or modify create_user method in UserManager class.

2023-04-14 21:29 UTC, zamaniamin commented on users/serializers.py
> +            user.is_active = False
Thanks for comment, please submit your code.

2023-04-15 20:41 UTC, MohammadShapouri requested changes
Deactivating users during creation (Prevents an additional query).

2023-04-15 20:41 UTC, MohammadShapouri commented on users/serializers.py
> +            user.save()
```suggestion

```

2023-04-15 20:41 UTC, MohammadShapouri commented on users/views.py
> +            user = serializer.save()
```suggestion
            # Also deactivate the user object
            user = serializer.save(is_active=False)
```

2023-04-16 06:51 UTC, parsariyahi commented on users/views.py
> +            user = serializer.save()
hi, I think there is no need to comment each action, it will be more clean if you just delete them.
```python
# Create the user object :|
user = serializer.save()
```

2023-04-16 16:34 UTC, zamaniamin commented on users/views.py
> +            user = serializer.save()
> hi, I think there is no need to write comment for each action, it will be cleaner if you just delete them.
> 
> ```python
> # Create the user object :|
> user = serializer.save()
> ```

This is not a commercial project, our goal is to teach and practice. Most of the comments are for reminders and education.

2023-04-16 16:45 UTC, zamaniamin commented on users/views.py
> +            user = serializer.save()
> 

nice!

2023-04-16 18:40 UTC, parsariyahi commented on users/views.py
> +            user = serializer.save()
I didn't mean that, if you code this for education, it's better to write a code like you write it in a production and high level code, there is millions of tutorials that do the education, but a few tell you what a real production level project looks like.

writing something like this
```python
# Create the user object
user = serializer.save()
```
is the same with this
```python
# define variable b
b = 10
```
and this is not something good for education, this is my opinion and I think this is over-commenting

2023-04-19 02:43 UTC, aminm08 commented on users/serializers.py
> +            token = Token.objects.get(key=data.get('token'))
Why don't we use the token that is already in the URL and delete the token field instead of getting the token again?

``` suggestion
            token = Token.objects.get(key=self.context['token'])
```

2023-04-19 02:45 UTC, aminm08 commented on users/views.py
> +        serializer = self.get_serializer(data=request.data)
And we can send the token within the context here.

```suggestion
        serializer = self.get_serializer(data=request.data, context={'token':kwargs.get('token')})
```

2023-04-20 13:20 UTC, zamaniamin commented on users/views.py
> +        serializer = self.get_serializer(data=request.data)
Nice, thank you.

2023-04-21 12:47 UTC, aminm08 approved these changes

2023-04-21 12:52 UTC, merged